// Generated by CoffeeScript 1.3.3

$(function() {
  var warning;
  window.socket = io.connect('127.0.0.1:8000/chat');
  warning = void 0;
  socket.on('has-error', function(data) {
    if (warning != null) {
      clearTimeout(warning);
    }
    return (function() {
      ($('#warning')).text(data.info);
      ($('.alert')).slideDown();
      return warning = setTimeout((function() {
        return ($('.alert')).slideUp();
      }), 1000);
    })();
  });
  if (localStorage.name != null) {
    socket.emit('set-name', {
      name: localStorage.name
    });
    ($('#name')).val(localStorage.name);
  }
  return ($('#name')).bind('input', function() {
    socket.emit('set-name', {
      name: ($('#name')).val()
    });
    return localStorage.name = ($('#name')).val();
  });
});
