// Generated by CoffeeScript 1.3.3
var auth, f2, one_day, socket;

f2 = function(num) {
  if (num < 10) {
    return "0" + num;
  } else {
    return "" + num;
  }
};

one_day = function(mark) {
  var date, day, hour, min, month, that, year;
  day = new Date(mark);
  year = (f2(day.getFullYear())).slice(2, 4);
  month = f2(day.getMonth());
  date = f2(day.getDate());
  hour = f2(day.getHours());
  min = f2(day.getMinutes());
  return that = {
    str: "" + year + " " + month + "-" + date + " " + hour + ":" + min,
    mark: String(mark)
  };
};

socket = io.connect('127.0.0.1:8000/log');

socket.on('has-error', function(data) {
  return console.dir(data.info);
});

auth = function(name, passwd) {
  return socket.emit('login-auth', {
    name: name,
    auth: passwd
  });
};

$(function() {
  var count, current, days, jump, start, step;
  start = 1340121600000;
  step = 86400000;
  current = new Date().getTime();
  jump = start;
  days = $('#days');
  count = 0;
  while (jump < current && count < 100) {
    (function() {
      var now;
      now = one_day(jump);
      days.append("<li id='" + now.mark + "'>" + now.str + "</li>");
      return $('#' + now.mark).click(function() {
        return socket.emit('topic-list', {
          mark: now.mark
        });
      });
    })();
    jump += step;
    count += 1;
  }
  socket.on('topic-list', function(list) {
    $('#topics').html('');
    return list.forEach(function(item) {
      $('#topics').append("        <li id='topic" + item.mark + "'>          " + item.date + "-" + item.time + " " + item.name + "          <i id='rm-topic" + item.mark + "'>rm</i>          <br>" + item.text + "        </li>");
      $("#topic" + item.mark).click(function() {
        return socket.emit('post-list', {
          mark: item.mark
        });
      });
      return $("#rm-topic" + item.mark).click(function() {
        socket.emit('rm-topic', {
          mark: item.mark
        });
        return false;
      });
    });
  });
  socket.on('post-list', function(list) {
    $('#posts').html('');
    return list.forEach(function(item) {
      $("#posts").append("        <li id='post" + item.mark + "'>          " + item.date + "-" + item.time + " " + item.name + "          <i id='rm-post" + item.mark + "'>rm</i>          <br>" + item.text + "        </li>");
      return $("#rm-post" + item.mark).click(function() {
        socket.emit('rm-post', {
          topic: item.topic,
          mark: item.mark
        });
        return false;
      });
    });
  });
  socket.on('rm-topic', function(data) {
    return $('#topic' + data.mark).remove();
  });
  return socket.on('rm-post', function(data) {
    return $('#post' + data.mark).remove();
  });
});
